/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jarSampleLib;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("lib call");
        return true;
    }
}
